language: java
install: true
jdk:
    - oraclejdk8

env:
  global:
    - secure: "AqHzKhB75+By3+sPrkvRhp5Ah6sr+XfgmKcmIZqeXLL0U2/un9+4uxOpnJYbuI+OwHcdTQUtzLJpaR1Tu7kenJX0Fc4Jow5RybxbscVuJDqFs2WSOnfotlO637XEzgG9GRlkXlufYaWpfZDmDlzf7FVufT7wZ3SfyaL4GsHE4AmT3RzXXHYWbDDbApzGStFE9hklHF/GB5x91nrKU6HV9YPZy3+jeX/TIJF30O86KZ9gHvRa1/FJWZ+EoMjL/FlDC63tEWfiuU2v2GjN15jRDS/IZs4PDJZTCCEaco8gls4EHux/ujXIEXDkVZDniNxI7/iNspTTp/Uvl+wogZNeb4V1D1JTZk1za9yvC8i3bcqUccyfqUpMT8JY3AutHzjEc576aN32Pka9wKZgApx4pOCgJ+p1Rh9c8BpYvQqE0Vl88JPhbjZwaEv1HF3MUcmM0INlvKAElKmUfOhfsJt4vkK53UGQVfx+zIYCwV5NDfjskAqj4g28xXCAZA08nwTHnB+KUDhdXdyb1IzXSOk3MDJfjQYT3FDcSm3xcRbPZfFMW+mqhGCjJfAT3b+gyiUQjg7pGdoKkKguB3Cxzpn/1dEYMMkchOZ9pCqXUQMR3Rqy4ghecJ0sSWA1y/AHkQN4/YRJ7vD2Ph20eAQO9wzydS49Ec+YO2CeBBk5Z9z4kA4="
    - secure: "S7K5yeZ+qE8DEap771fDzfUP6xAp+INPo+FLYS+IqnOFxlsudwIdeyz/pqTYoNMbO1K7UuRoX0ht2NaKPFadR64EwEkecBdR+cfrgaLVE4L5xe53Rwc05uOYwhQi9+lJJ4adtirGV2t8eJeWWjbSIrmLBBJ1BTqAFsvSV1y8F/cg8ap7TyckyV822Qw8k1nAVnnsY87cmlQsM0VgDi7AyiQPpWKF6OgsIGT6Mlx2BGXHqYbEkee/Xq9ELEZbu+DDFlIxh+hCAkMiXArL9oRbUiGw635WCQxY0mR4UZlBLacwY/JDIRsPxcMfSLkEP7wzjBZW7zj+pQWxRhRDikF72QyM6oQPh2rUKo5X8Hlo3mojAK49RCkCm7bKpOOOI7sZlcaCAaWWw1ziKXXgue95IhM2JSjBrLjoi4hFAgoQe1HuYx1PISFs3E69u8v+qZI/8oZPmky5RAxku1Ajci2BGCYeNW98hiW+/inMHtb7BJl+dNhfQuUh0hBGc1HKc1h1PBjS22JEUi2QPSb4loKHbZjbQadYA45WI5mXiyyo7GOVH+zNmdzLIMOhRreDi4nTSu49h4iBGC71P6ZS+JHxhTmh1R2bSGGaCx4J9fHILU4HNOEdbU0D2yc4/E2XaexKtsSqOCJ+oU/OmUSP47rvw+ntTTe+GrUKjYJI2luI0ao="

cache:
  directories:
    - $HOME/.gradle
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install oracle-java8-installer
    - sudo apt-get install oracle-java7-installer

before_script:
    - ./gradlew --version
script:
    - ./gradlew clean assemble check --info

after_success:
    - chmod ugo+x .buildscript/deploy_artifacts.sh
    - .buildscript/deploy_artifacts.sh
    - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
